[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "riffpay-backend"
version = "0.1.0"
description = "Doctor Little AI Backend"
authors = [{ name = "You" }]
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]
